### ISSUE TITLE
Manga: Time since latest chapter

### ISSUE THREAD

**Issue by AbandonedCart** [RepoDevil/Mr.Matagi#10]
The data available provided the latest chapter release and, despite numerous attempts to sabotage it upstream, works pretty well. Despite that being enough, I do like @Mathew20kdroid 's idea to create a prediction of upcoming release dates. Let's crunch some numbers and find out if it would be accurate.

**Comment by AbandonedCart** [comment]
Chainsaw Man

    Chapter 149 – Nov. 21, 2023

    Chapter 150 – Nov. 28, 2023

    Chapter 151 – Dec. 5, 2023

    Chapter 152 – Dec. 12, 2023

    Chapter 153 – Dec. 19, 2023

    Chapter 154 – Dec. 26, 2023

So we could assume the next release would be 7 days.

**Comment by AbandonedCart** [comment]
My Dress Up Darling is monthly, with chapter 101 being Feb 16 and chapter 102 on March 14.

**Comment by Mathew20kdroid** [comment]
Yeah, most of the manga and Manhwas are released on a proper schedule so it will be sorta easy to predict the next date.....
If the chapter is not released on that date then checking the previous few chapters for the bigger time gap in release and adjusting the date accordingly will be nice.....

**Comment by AbandonedCart** [comment]
I have a feeling if the prediction is wrong, it would be better to call it delayed than try to estimate a new release date. I've seen some get delayed and the delay turns into a whole season.

**Comment by Mathew20kdroid** [comment]
Yeah, calling it **delayed** is the best option.....its better not to make too many complications 😅
Now that i think about it we can't normally predict the delay period so that really is the best option.....

**Comment by AbandonedCart** [comment]
I have the code more or less established. I should be able to test it out tonight

**Comment by AbandonedCart** [comment]
I could not reliably retrieve a single series where they listed more than 2 chapters in a row and the two in a row were almost never recent. It's basically a lost cause.

**Comment by Mathew20kdroid** [comment]
I really hoped this would work, but it was worth a try.... thanks for all time and work you put into this.... really appreciate it....

**Comment by Mathew20kdroid** [comment]
> I could not reliably retrieve a single series where they listed more than 2 chapters in a row and the two in a row were almost never recent. It's basically a lost cause.

Will it work if it tries to retrieve one chapter at a time for a manga and the previous one according and then compare them....

**Comment by AbandonedCart** [comment]
The problem is that it doesn't have subsequent chapters. It will have like 101, then 99, then 98, but then 95

**Comment by AbandonedCart** [comment]
I haven't given up on this one. I wanted to get the other stuff I had answers for out of the way first.

**Comment by AbandonedCart** [comment]
It will be interesting to see if they understand the code well enough upstream to realize @minsoramune is returning all empty values.

**Comment by Mathew20kdroid** [comment]
I don't know what particular method they are using but the latest beta of **Mihon** managed to do this ....their predicted dates are not to the point accurate but close enough.....
![Screenshot_20240415-225434.png](https://github.com/RepoDevil/Mr.Matagi/assets/71634955/cde50f27-a6b1-4df2-8d92-0b3b196c108b)

**Comment by AbandonedCart** [comment]
I'm not entirely shocked. Their codebase is probably two years ahead of this one.

**Comment by Mathew20kdroid** [comment]
I looked up into that and found this
https://github.com/mihonapp/mihon/blob/main/domain/src/main/java/tachiyomi/domain/manga/interactor/FetchInterval.kt#L44C53-L44C55

No Idea what this is😅...not familiar with programming and stuff

**Comment by AbandonedCart** [comment]
![Screenshot_20240416_000710](https://github.com/RepoDevil/Mr.Matagi/assets/1173913/da7247db-8482-4f28-88d9-2d631d6f3c50)

**Comment by AbandonedCart** [comment]
Less than an hour and @UmbrellaalAcademy does one of the ugliest hack jobs I've seen trying to submit this as https://github.com/rebelonion/Dantotsu/pull/363

**Comment by Mathew20kdroid** [comment]
😓

**Comment by Mathew20kdroid** [comment]
At least what you did was your own and genuinely from the start...

**Comment by AbandonedCart** [comment]
The part I don't get is all the arrogance and entitlement. 90% of the mistakes I've been fixing have been basic logic errors.

**Comment by AbandonedCart** [comment]
I rethought how I was going about this and realized it was drastically over-engineered and focusing on the wrong thing.

<details><summary>Chainsaw Man</summary>

![Screenshot_20240416_115522](https://github.com/RepoDevil/Mr.Matagi/assets/1173913/f6e99813-7226-4c08-aa9a-345f8c83a34c)
</details>

<details><summary>One Piece</summary>

![Screenshot_20240416_115454](https://github.com/RepoDevil/Mr.Matagi/assets/1173913/d596a002-eb51-4522-9bb4-cd785238784e)
</details>

<details><summary>My Dress-Up Darling</summary>

![Screenshot_20240416_115507](https://github.com/RepoDevil/Mr.Matagi/assets/1173913/f73c16d4-a6bb-404d-aba3-397015d902d6)
</details>

**Comment by AbandonedCart** [comment]
I need to add the part that checks against the current date still. It's going to show delayed, since there is no real way of knowing when it will be released. Everything is just a rough estimate.

**Comment by Mathew20kdroid** [comment]
I noticed the website does not have the release dates for all managa or manhwa...
Rebel mentioned he's planning on implementing a notification center for manga as well in the near future....
How about getting the chapter release dates for our selected manga from the notification center (when implemented) since it will have the chapter release dates.....(for when manga/Manhwa chapter release dates are not available via the website)
No need for internet connection as well as the data is available locally 

Also can switch to total local release date processing once there are enough chapter released (available in notification)...
(Just a suggestion)

**Comment by AbandonedCart** [comment]
It will depend on what that actually means.

Mihon uses a combination of user data and MangaUpdates data to create their predictions. If you notice when you view an extension, items all have release dates. They are combining that data with the stuff from the API to create a wider range of points to average together. For all I know, it's just a clone of that.

**Comment by AbandonedCart** [comment]
No worries. You didn't say anything rude. I thought you were talking about a future feature and was saying you never know if what was planned is exactly what you get.
