### ISSUE TITLE
Movie and Tv series Support??

### ISSUE THREAD

**Issue by OtakuVadER** [RepoDevil/Mr.Matagi#15]
Okay so i just got an better idea than that blank entry one
So if you know there is adult only mode in dantotsu so if it is possible to add an option to switch to tmdb api in settings 
An option like that can make dantotsu an all in one media watching application 

It's harder than blank entry but 
It's worth giving a try

**Comment by AbandonedCart** [comment]
I'm not sure I want to head that direction. There's already so many apps like that and there is a lot of risk to overstep the line between an app to track what you read and watch into a fancy Limewire (the app to share media before torrents).

**Comment by AbandonedCart** [comment]
Yeah, so you can look inside extension now.

**Comment by AbandonedCart** [comment]
There's a whole mess of what if scenarios trying to work back from the extension. For now, you can open the extension page and search inside them. Selecting an item launches the search for the item from anilist. It's a couple more steps than I plan for the final version. It's progress, though.

**Comment by OtakuVadER** [comment]
Yea that's true it will be crossing the line

**Comment by AbandonedCart** [comment]
Since we have an extension search now, all that's left is trying to find a better way to launch items found with it. Since the extension page is linked to the main popup, that seems convenient enough to not add a blank item.

**Comment by OtakuVadER** [comment]
![IMG_20240418_210539](https://github.com/RepoDevil/Mr.Matagi/assets/88473676/155d0e2c-801f-442f-889b-21ffc071e502)
See this movie mode button then clicking this and we will get
![2024041821034266](https://github.com/RepoDevil/Mr.Matagi/assets/88473676/06f37eab-b88c-412e-b0b2-a0db7191ab75)
And this is like my concept select your source and then there is search area which is wrong title one using which we can search within the extension and after choosing what we want to watch clicking it opens a page which shows episode

**Comment by AbandonedCart** [comment]
Oh, ok. That's what I thought you had meant yesterday.

**Comment by OtakuVadER** [comment]
Yea yea smtg like this

**Comment by AbandonedCart** [comment]
Done

**Comment by OtakuVadER** [comment]
Done in the sense you made it? Or you are gonna work on it?

**Comment by OtakuVadER** [comment]
Looking forward to it

**Comment by OtakuVadER** [comment]
Well it's not working as it should be
Selecting the movie just led to search it in manga or anime search

**Comment by AbandonedCart** [comment]
Yeah. That part isn't finished yet. I still need to add all the code to play it directly, since all of that is built on the assumption you started with an anilist item.

**Comment by OtakuVadER** [comment]
Well I'll be looking forward for the end result

**Comment by AbandonedCart** [comment]
Seems like playing an item directly would be a little bit more of a rewrite than the use really justifies. Almost every aspect of the app is tied to media items collected from anilist. The extensions, on the other hand, aren't based on anilist. As a means to tell you if an extension has an item, it works. As a way to bypass the anilist part of the app and play random files, it would take days to break all the dependency enough to not crash and then you lose most of the app functionality.

**Comment by OtakuVadER** [comment]
Ohk got it so just let's leave this request and work on novel one

**Comment by AbandonedCart** [comment]
Closing this as "somewhat complete"

The current design lets you see what's in an extension and try to reverse match it to the app.

**Comment by AbandonedCart** [comment]
It finally git me why this didn't seem as amazing a feature as it should. You still have to pick the extension. Why shouldn't the app tell me which extensions?

**Comment by OtakuVadER** [comment]
So now working on novels??
